<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Axon.SqlServer</RootNamespace>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>GoAxon.Store.SqlServer</PackageId>
        <Description>SQL Server-backed job storage for Axon.Server.</Description>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Dapper" Version="2.1.66" />
      <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Axon.Server\Axon.Server.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
