blank_issues_enabled: true
contact_links:
  - name: Contributing guide
    url: https://github.com/housgh/Axon/blob/master/CONTRIBUTING.md
    about: Read this before proposing a change to a public interface.
